/* 部门结构数据 */
export default [{
	name: '软件基础部',
	personnel: [{
		icon: '../../static/img/uni@2x.png',
		name: "胡靖",
		work: "软件测试工程师"
	}, {
		icon: '../../static/img/uni@2x.png',
		name: "彭好杰",
		work: "软件开发工程师"
	}, {
		icon: '../../static/img/uni@2x.png',
		name: "贾俊",
		work: "经理"
	}, {
		icon: '../../static/img/uni@2x.png',
		name: "毕文龙",
		work: "开发工程师"
	}, {
		icon: '../../static/img/uni@2x.png',
		name: "杨坤",
		work: "开发工程师"
	}, {
		icon: '../../static/img/uni@2x.png',
		name: "沈志慧",
		work: "测试工程师"
	}, {
		icon: '../../static/img/uni@2x.png',
		name: "王燕杰",
		work: "高级软件开发工程师"
	}],
	department: []
}, {
	name: '同是科技',
	personnel: [{
		icon: '../../static/img/uni@2x.png',
		name: "刘国彬",
		work: "总经理"
	}],
	department: [{
		name: '运营体系',
		show: false,
		personnelItem: [{
			icon: '../../static/img/uni@2x.png',
			name: "苏武平",
			work: "副总经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "杨琳",
			work: "经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "刘忠娜",
			work: "副经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "顾洁慧",
			work: "出纳"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "孙丽君",
			work: "会计"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "徐明",
			work: "经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "王辉",
			work: "QA工程师"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "杨勇",
			work: "经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "耿丽阁",
			work: "副经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "徐燕",
			work: "人事专员"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "徐鹦",
			work: "人事助理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "管蓓蓉",
			work: "主任"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "夏屹",
			work: "行政主管"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "王坤",
			work: "经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "李婷婷",
			work: "行政专员"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "人事流程",
			work: "IT管理员"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "业务流程",
			work: "IT管理员"
		}],
		departmentItem: [{
			name: '财务部',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '质量管理部',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '人力资源部',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '总经理办公室',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '综合管理部',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '流程管理',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}]
	}, {
		name: '营销中心',
		show: false,
		personnelItem: [{
			icon: '../../static/img/uni@2x.png',
			name: "孙磊",
			work: "营销中心总经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "张宇晨",
			work: "经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "王朝晖",
			work: "客户经理"
		}],
		departmentItem: [{
			name: '浙江区域服务支持中心',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '重庆区域服务支持中心',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '青岛区域服务支持中心',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '咨询部',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '地铁工程部',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '市政工程部',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}]
	}, {
		name: '工程中心',
		show: false,
		personnelItem: [],
		departmentItem: []
	}, {
		name: '研究院',
		show: false,
		personnelItem: [],
		departmentItem: []
	}, {
		name: '分支机构',
		show: false,
		personnelItem: [],
		departmentItem: []
	}]
}, {
	name: '睿语公司',
	personnel: [],
	department: [{
		name: '睿语总务部',
		show: false,
		personnelItem: [],
		departmentItem: []
	}, {
		name: '睿语产品咨询部',
		show: false,
		personnelItem: [],
		departmentItem: []
	}, {
		name: '睿语IT研发部',
		show: false,
		personnelItem: [],
		departmentItem: []
	}, {
		name: '睿语销售部',
		show: false,
		personnelItem: [],
		departmentItem: []
	}]
}, {
	name: '湖北公司',
	personnel: [{
		icon: '../../static/img/uni@2x.png',
		name: "闫伟",
		work: "总经理"
	}],
	department: [{
		name: '湖北综合管理部',
		show: false,
		personnelItem: [{
			icon: '../../static/img/uni@2x.png',
			name: "李卢婕",
			work: "行政管理"
		}],
		departmentItem: []
	}, {
		name: '湖北项目管理部',
		show: false,
		personnelItem: [{
			icon: '../../static/img/uni@2x.png',
			name: "林桂松",
			work: "系统工程师"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "明鹏",
			work: "武汉项目组"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "王浩",
			work: "经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "邱志",
			work: "开发工程师"
		}],
		departmentItem: [{
			name: '武汉地铁项目部',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '长丰大道项目部',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}, {
			name: '东湖通道项目部',
			show: false,
			personnelItem1: [],
			departmentItem1: []
		}]
	}, {
		name: '湖北销售部',
		show: false,
		personnelItem: [{
			icon: '../../static/img/uni@2x.png',
			name: "余卫锋",
			work: "华中分公司总经理助手"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "朱江",
			work: "客户经理"
		}],
		departmentItem: []
	}]
}, {
	name: '若泰公司',
	personnel: [{
		icon: '../../static/img/uni@2x.png',
		name: "黄正家",
		work: "总经理"
	}, {
		icon: '../../static/img/uni@2x.png',
		name: "刘建军",
		work: "经理"
	}, {
		icon: '../../static/img/uni@2x.png',
		name: "邹晶",
		work: "行政专员"
	}],
	department: [{
		name: '若泰产品开发1部',
		show: false,
		personnelItem: [{
			icon: '../../static/img/uni@2x.png',
			name: "李波波",
			work: "软件开发工程师"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "梁富",
			work: "软件开发工程师"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "王文君",
			work: "高级软件开发工程师"
		}],
		departmentItem: []
	}, {
		name: '若泰技术咨询部',
		show: false,
		personnelItem: [{
			icon: '../../static/img/uni@2x.png',
			name: "党维维",
			work: "副总经理"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "陈永青",
			work: "咨询工程师"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "李想",
			work: "安全工程师"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "陶建城",
			work: "咨询工程师"
		}, {
			icon: '../../static/img/uni@2x.png',
			name: "陈聪",
			work: "咨询工程师"
		}],
		departmentItem: []
	}, {
		name: '若泰营销部',
		show: false,
		personnelItem: [],
		departmentItem: []
	}, {
		name: '若泰方案设计部',
		show: false,
		personnelItem: [],
		departmentItem: []
	}, {
		name: '若泰产品开发2部',
		show: false,
		personnelItem: [],
		departmentItem: []
	}]
}]
